layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social media:
  # instagram: reja_khan_

topics:
  - name: GitHub
    web_url: https://github.com/topics/css
    image_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
    
  - name: TechOlympics
    web_url: https://techolympics.org/
    image_url: https://techolympics.org/wp-content/uploads/2019/10/activate-3.png
    
  - name: CincyHacks
    web_url: https://cincyhacks.com/
    image_url: https://cincyhacks.com/assets/logo.png
